# Generated by Django 5.1 on 2024-08-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='authors/%Y/%m/%d/')),
                ('libraries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Authors', to='libraries.library')),
            ],
        ),
    ]
